### ISSUE TITLE
TypeError: render() got an unexpected keyword argument 'format'

### ISSUE THREAD

**Issue by obook** [cobacdavid/trifusionviz#1]
Hello David,
I got an error runing the example under Linux:

```
  _t.sortie("exemple_sortie")
  File "/usr/local/lib/python3.8/dist-packages/trifusionviz/trifusionviz.py", line 113, in sortie
    self.graphe.render(filename=nom_fichier, format=format)
TypeError: render() got an unexpected keyword argument 'format'_
```
graphviz version 2.43.0

Regards,
Olivier

**Comment by cobacdavid** [comment]
Hi Olivier,
can you check your python graphviz library version?
```bash
$ pip3 list |grep ^graphviz
graphviz            0.15
```
To update: `$ pip3 install graphviz --upgrade`

I think this is the source of the issue.

**Comment by obook** [comment]
Hello David.
graphviz for Python3 was 0.8.4 from ubuntu repositories. I have remove this version and installed with pip3, your code run great.
Thank you.
Olivier

```
$ pip3 list |grep ^graphviz
graphviz                0.8.4

sudo apt remove python3-graphviz
sudo -H pip3 install graphviz --upgrade

$ pip3 list |grep ^graphviz
graphviz                0.15
```
